name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch: {}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        pip install pytest

    - name: Run tests
      run: |
        mkdir -p ci-artifacts
        pytest --maxfail=1 --disable-warnings -q | tee ci-artifacts/tests.txt
      continue-on-error: true

    - name: Run fuzzing
      run: |
        mkdir -p ci-artifacts
        python fuzz.py | tee ci-artifacts/fuzz_output.txt
      continue-on-error: true

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: ci-results
        path: ci-artifacts
